[package]
name = "fft"
version = "0.4.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/fft"
homepage = "https://github.com/hilbert-space/fft"
description = "Use the DFT package instead."

[dependencies]
dft = "*"
