[package]
name = "fft"
version = "0.3.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/fft"
homepage = "https://github.com/hilbert-space/fft"
description = "FFT."
